services:
  web:
    image: nginx:1.27.4-alpine3.21-slim
    volumes:
      - ./:/var/www
      - ./docker/development/nginx/nginx.conf:/etc/nginx/nginx.conf:ro
      - ./ssl/cert.crt:/etc/ssl/certs/cert.crt
      - ./ssl/key.key:/etc/ssl/private/key.key
    ports:
      - 80:80
      - 443:443
    networks:
      - laravel-development

  php-fpm:
    build:
      context: .
      dockerfile: ./docker/common/php-fpm/Dockerfile
      target: development
      args:
        TARGET_ENV: development
        XDEBUG_ENABLED: ${XDEBUG_ENABLED:-true}
        XDEBUG_MODE: develop,coverage,debug,profile
        XDEBUG_HOST: ${XDEBUG_HOST:-host.docker.internal}
        XDEBUG_IDE_KEY: ${XDEBUG_IDE_KEY:-DOCKER}
        XDEBUG_LOG: /dev/stdout
        XDEBUG_LOG_LEVEL: 0
    volumes:
      - ./:/var/www
    networks:
      - laravel-development

  postgres:
    image: postgres:17.4
    ports:
      - "${POSTGRES_PORT:-5432}:5432"
    env_file:
      - .env
    environment:
      - POSTGRES_DB=${DB_DATABASE}
      - POSTGRES_USER=${DB_USERNAME}
      - POSTGRES_PASSWORD=${DB_PASSWORD}
    volumes:
      - postgres-data-development:/var/lib/postgresql/data
    networks:
      - laravel-development

  redis:
    image: redis:7.4.2-alpine3.21
    networks:
      - laravel-development

  vite:
    image: node:23.10.0-alpine3.21
    working_dir: /var/www
    volumes:
      - ./:/var/www
    command: sh -c "npm install && npm run dev"
    environment:
      - CHOKIDAR_USEPOLLING=true
      - WDS_SOCKET_PORT=5173
    ports:
      - "5173:5173"
    networks:
      - laravel-development


networks:
  laravel-development:

volumes:
  postgres-data-development:
